### ISSUE TITLE
Many errors

### ISSUE THREAD

**Issue by Karaulov** [ChiefOfGxBxL/Ice-Sickle#59]
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
undefined: undefined

[ОК]

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: Cannot read property 'close' of null
    at EventEmitter.<anonymous> (C:\Users\Karaul0v\AppData\Local\Programs\icesickle\resources\electron.asar\browser\rpc-server.js:468:39)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at WebContents.<anonymous> (C:\Users\Karaul0v\AppData\Local\Programs\icesickle\resources\electron.asar\browser\api\web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

[ОК]

**Comment by QGB** [comment]
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Cannot find module 'universalify'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\qgb\AppData\Local\Programs\icesickle\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\qgb\Documents\icesickle\scripting\languages\JASS\node_modules\fs-extra\lib\fs\index.js:4:11)
    at Object.<anonymous> (C:\Users\qgb\Documents\icesickle\scripting\languages\JASS\node_modules\fs-extra\lib\fs\index.js:100:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\qgb\Documents\icesickle\scripting\languages\JASS\node_modules\fs-extra\lib\index.js:6:3)
    at Object.<anonymous> (C:\Users\qgb\Documents\icesickle\scripting\languages\JASS\node_modules\fs-extra\lib\index.js:21:3)

[确定]

**Comment by QGB** [comment]
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: Cannot read property 'close' of null
    at EventEmitter.<anonymous> (C:\Users\qgb\AppData\Local\Programs\icesickle\resources\electron.asar\browser\rpc-server.js:468:39)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at WebContents.<anonymous> (C:\Users\qgb\AppData\Local\Programs\icesickle\resources\electron.asar\browser\api\web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

[确定]
